version: '3'

volumes:
  postgres_data: {}

services:
  nginx:
    image: nginx
    container_name: ng01
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./.static_root/:/.static_root/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html/:/etc/nginx/html/
      - ./gunicorn/:/gunicorn/
    depends_on:
      - django01
      - django02
      - django03
    environment:
      - TZ=Asia/Seoul

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    volumes:
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./redis/cache:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf

  db:
    image: postgres:14.2
    container_name: ps01
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=LOCALDB
      - POSTGRES_USER=localdb_owner
      - POSTGRES_PASSWORD=localdb_owner1!
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    ports:
      - "5432:5432"
    command: -p 5432

  django01:
    build:
      context: .
      dockerfile: ./Dockerfile.DjangoMain
    container_name: dg01
    restart: always
    volumes:
      - ./source/:/app/
      - ./.static_root/:/.static_root/
      - ./gunicorn/:/gunicorn/
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=source.settings.developer
      - DJANGO_DEBUG=True
      - TZ=Asia/Seoul
    command: bash -c "
      python3 manage.py collectstatic --noinput &&
      (yes | python3 manage.py makemigrations) &&
      python3 manage.py migrate &&
      gunicorn source.wsgi:application --bind unix:/gunicorn/gunicorn01.sock -c /gunicorn/prod.py"

  django02:
    build:
      context: .
      dockerfile: ./Dockerfile.DjangoMain
    container_name: dg02
    restart: always
    volumes:
      - ./source/:/app/
      - ./.static_root/:/.static_root/
      - ./gunicorn/:/gunicorn/
    depends_on:
      - db
      - django01
    environment:
      - DJANGO_SETTINGS_MODULE=source.settings.developer
      - DJANGO_DEBUG=True
      - TZ=Asia/Seoul
    command: bash -c "
      gunicorn source.wsgi:application --bind unix:/gunicorn/gunicorn02.sock -c /gunicorn/prod.py"

  django03:
    build:
      context: .
      dockerfile: ./Dockerfile.DjangoMain
    container_name: dg03
    restart: always
    volumes:
      - ./source/:/app/
      - ./.static_root/:/.static_root/
      - ./gunicorn/:/gunicorn/
    depends_on:
      - db
      - django01
    environment:
      - DJANGO_SETTINGS_MODULE=source.settings.developer
      - DJANGO_DEBUG=True
      - TZ=Asia/Seoul
    command: bash -c "
      gunicorn source.wsgi:application --bind unix:/gunicorn/gunicorn03.sock -c /gunicorn/prod.py"
