# Generated by Django 4.0.2 on 2022-06-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '사용자 권한',
                'db_table': 'users_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='소셜사용자_id')),
                ('email', models.EmailField(max_length=254, verbose_name='사용자 이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인 일자')),
                ('withdrawal_at', models.DateTimeField(auto_now=True, null=True, verbose_name='탈퇴 일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='user', to='users.userrole', verbose_name='사용자 권한')),
            ],
            options={
                'verbose_name_plural': '회원정보',
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
